# adapted from https://github.com/headmelted/vscode/blob/a57e613e9e7d2fdb3917502cb98bbd1eaef8c058/.travis.yml

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(\-[a-zA-Z0-9]+)?$/

language: node_js
node_js: 8

env:
  global:
    - secure: Kb7VJcRSoZ+yQIRo+XBWS2sPl+4GPPZ+1gbodIhhM+AQty+8B+g47EjF5cfo0vJpjdNA0a0MxgLb35FkNwCnOk5ejZKsA1ai4rGjTkQd6AcCLa0byfr0ez4ZDKAjVyFWJ97L4+sBfX2O7VA08iG8+SbnuLGNcbKyWmHuMVe7oi4+bVvtSVYFmDBFQGLsvGejfoGnQz3xhoqNQm9U8ne1/SdDnkTrm6TOXfVcGeRyspPhu9YpyivWcbuqX0wlyHHnsxADEKsi1lvfN2n8oha9kefhP/Kn7dC6LqKtHFFF9Holtx8BwnP/d72vBwazpe1qFUh/Fh2K/MJEL+w96W/8V/ROZ8OiRK7gfgTmY9ybiFs/vLE039185BdBh5yJWhZNJsyO5lH1cNtcy29H6Y0Fmii1GxMLXDR48/NpVeb9/0QS3qXE3IPt7DvMYsmkvRhbaOpMojiv0eA7BbQo17+G02+qaOUKZ4H/Pn/WUffUTNJzasj9cDoU1RtwQ45635BIx9JGAhtJ9uFaC5Z8gt5QvoO5nrjkWfUAEyFMXZisPtVy9roVkyWDwIkmxNWcUq1D/hMSIw6MM24zO77IbjeeZmUuspQT7mHORbCZIotdN84L5WTIaorvhXam0ZhBXFab68bvJhheKnK6091E3rbXkdDh5m+N+t3afGdGVUhS4Qw=

# define OSes with all settings so the build matrix is shorter
include: &osx
  sudo: false
  os: osx
  addons:
    apt:
      sources: 
      - 'ubuntu-toolchain-r-test'
      packages:
      - gcc-4.9
      - g++-4.9  
  env:
  - LABEL=OSX
    ARCH=x64

include: &linux
  sudo: false
  os: linux
  addons:
    apt:
      sources: 
      - 'ubuntu-toolchain-r-test'
      packages:
      - gcc-4.9
      - g++-4.9  
  env:
  - LABEL=LINUX
    ARCH=x64
    EXPORT_CXX=g++-4.9
    EXPORT_CC=gcc-4.9

include: &arm
  sudo: required
  os: linux
  addons:
    apt:
      sources: 
      - 'ubuntu-toolchain-r-test'
      packages:
      - gcc-4.9
      - g++-4.9  
      - gcc-arm-linux-gnueabihf
      - g++-arm-linux-gnueabihf
  env:
  - LABEL=ARM
    ARCH=arm
    EXPORT_CXX=g++-4.9
    EXPORT_CC=gcc-4.9
    EXPORT_PRE_CXX=arm-linux-gnueabihf-g++
    EXPORT_PRE_CC=arm-linux-gnueabihf-gcc
    EXPORT_PRE_LINK=arm-linux-gnueabihf-g++
    EXPORT_PRE_AR=arm-linux-gnueabihf-ar

matrix:
  include:
    - <<: *linux
    - <<: *osx
    - <<: *arm

before_install:
# Export neccessary env vars so gyp finds the compilers
- if [[ -n "${EXPORT_CXX}" ]]; then export CXX="${EXPORT_CXX}"; fi
- if [[ -n "${EXPORT_CC}" ]]; then export CC="${EXPORT_CC}"; fi
# get commit message
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
# put local node_modules on PATH
- export PATH=./node_modules/.bin/:$PATH
# put global node-gyp on PATH
- npm install -g node-gyp

- PUBLISH_BINARY=false
# if we are building a tag then publish
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
# or if we put [publish binary] in the commit message
- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;

install:
# install dependencies
- npm install

script:
# for cross-compilation x64=>ARM make the required compilers known
- if [[ -n "${EXPORT_PRE_CXX}" ]]; then export CXX="${EXPORT_PRE_CXX}"; fi
- if [[ -n "${EXPORT_PRE_CC}" ]]; then export CC="${EXPORT_PRE_CC}"; fi
- if [[ -n "${EXPORT_PRE_AR}" ]]; then export AR="${EXPORT_PRE_AR}"; fi
- if [[ -n "${EXPORT_PRE_LINK}" ]]; then export LINK="${EXPORT_PRE_LINK}"; fi
- |
  if [[ $PUBLISH_BINARY == true ]]; then
    echo "publishing binary"
    node ci/prebuild.js
  fi

after_success:
- echo "all done!"
