# adapted from https://github.com/headmelted/vscode/blob/a57e613e9e7d2fdb3917502cb98bbd1eaef8c058/.travis.yml

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

language: node_js

env:
  global:
    - secure: S5ZX8U0U7xQwhZdsXMRAr3H88QqIvDc0P8wdZSZF7aO5yFl+EsaadGGN+ptWKWpOdOsgLo4U/jXXq/l1HJSVitKBZZNwiSOVNMG1nu+a4uSRIHY0qN6dWBpgLgTFBfa3Jldd2+E94zur+UBla82m9aktL+PuvnU7FI4tmA4wR9+zGAM1e3SC8eosNsyzIQFS3oPocMX0/gYh9KXKwra9Qjs2RSQMXarjbehNRh4za5nJ5ySAKTopV9WiBQupRj+ERXWlY3fR8J/Bv/uQU+On2OLKZEWV2hU39rNrMqnp6Lf5Mv6O24XnIRxjI5dvdIxY753SnzjfQUMXtdDbDF7TQpbXDll2e7Nn8WYchncqcbWC9Aa7MayaPTdbiVQRDu3DKa5cTQg2KSO89euspZlGMlimbZnyf7EJPLlqchjFPQTsOCyrrxgBoxV/sPBfRJnbjw/8jJ0lnEmnz49vdpsX+/QsmkWZ/HX8brOJITzIWneyHiWZxJkG7NdRT0c1dfl+UheHLV7rEnEXdzrxLT+M6X6nE9lIEoWcDqDzD0OObNqahoNEcHZzcw8L6WfzU8HFfLjs2i+5TqrDkvPnwaq/Vdzmy8fl9OY5Kjb1C68xd1nh2tQCSNuQCAGfeWIQ7nncKZbKQxXOlqtaK1PdLtzLHKYLhCTM6fP23RjBGrelHgU=

# define OSes with all settings so the build matrix is shorter
include: &osx
  sudo: false
  os: osx
  addons:
    apt:
      sources: 
      - 'ubuntu-toolchain-r-test'
      packages:
      - gcc-4.9
      - g++-4.9  
  env:
  - LABEL=OSX
    ARCH=x64

include: &linux
  sudo: false
  os: linux
  addons:
    apt:
      sources: 
      - 'ubuntu-toolchain-r-test'
      packages:
      - gcc-4.9
      - g++-4.9  
  env:
  - LABEL=LINUX
    ARCH=x64
    EXPORT_CXX=g++-4.9
    EXPORT_CC=gcc-4.9

include: &arm
  sudo: required
  os: linux
  addons:
    apt:
      sources: 
      - 'ubuntu-toolchain-r-test'
      packages:
      - gcc-4.9
      - g++-4.9  
      - gcc-arm-linux-gnueabihf
      - g++-arm-linux-gnueabihf
  env:
  - LABEL=ARM
    ARCH=arm
    EXPORT_CXX=g++-4.9
    EXPORT_CC=gcc-4.9
    EXPORT_PRE_CXX=arm-linux-gnueabihf-g++
    EXPORT_PRE_CC=arm-linux-gnueabihf-gcc
    EXPORT_PRE_LINK=arm-linux-gnueabihf-g++
    EXPORT_PRE_AR=arm-linux-gnueabihf-ar

matrix:
  include:
  - <<: *osx
    node_js: 4
  - <<: *osx
    node_js: 6
  - <<: *osx
    node_js: 8
  
  - <<: *linux
    node_js: 4
  - <<: *linux
    node_js: 6
  - <<: *linux
    node_js: 8
  
  - <<: *arm
    node_js: 4
  - <<: *arm
    node_js: 6
  - <<: *arm
    node_js: 8
    
before_install:
# Export neccessary env vars so gyp finds the compilers
- if [[ -n "${EXPORT_CXX}" ]]; then export CXX="${EXPORT_CXX}"; fi
- if [[ -n "${EXPORT_CC}" ]]; then export CC="${EXPORT_CC}"; fi
# get commit message
- COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
# put local node_modules on PATH
- export PATH=./node_modules/.bin/:$PATH
# put global node-gyp on PATH
- npm install -g node-gyp

- PUBLISH_BINARY=false
# if we are building a tag then publish
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
## or if we put [publish binary] in the commit message
#- if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;

install:
# install dependencies
- npm install --production

script:
# for cross-compilation x64=>ARM make the required compilers known
- if [[ -n "${EXPORT_PRE_CXX}" ]]; then export CXX="${EXPORT_PRE_CXX}"; fi
- if [[ -n "${EXPORT_PRE_CC}" ]]; then export CC="${EXPORT_PRE_CC}"; fi
- if [[ -n "${EXPORT_PRE_AR}" ]]; then export AR="${EXPORT_PRE_AR}"; fi
- if [[ -n "${EXPORT_PRE_LINK}" ]]; then export LINK="${EXPORT_PRE_LINK}"; fi
- node-pre-gyp configure --target_arch=${ARCH}
- node-pre-gyp build --target_arch=${ARCH}
- |
  if [[ $PUBLISH_BINARY == true ]]; then
    echo "publishing binary"
    node-pre-gyp package --target_arch=${ARCH}
    node-pre-gyp-github publish --release
  fi
- node-pre-gyp clean --target_arch=${ARCH}
- node-gyp clean --target_arch=${ARCH}

after_success:
- echo "all done!"